# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command to print Pipeline ID for the project"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  command_job:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id
workflows:
  command_workflows:
    jobs:
      - command_job